services:
  - type: web
    name: rag-iss
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 1 --timeout 180
    envVars:
      - key: CHROMA_DIR
        value: /opt/render/project/src/chroma_db
      - key: GOOGLE_SHEET_CSV_URL
        value: https://docs.google.com/spreadsheets/d/1nwSzIkL-8Dmatx-dIS5zETsgZ4GPzaOJXguVDRqNbgQ/edit?usp=sharing
      - key: ANONYMIZED_TELEMETRY
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TOKENIZERS_PARALLELISM
        value: "false"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: OPENBLAS_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
